name: WoW TOC Updater
description: Updates Interface versions found in World of Warcraft TOC metadata files
branding:
  icon: tag
  color: green
inputs:
  addonDir:
    description: Directory containing the addon TOC file(s)
    default: .
  flavor:
    description: DEPRECATED - automatically determined from TOC file(s)
  beta:
    description: Include beta versions?
  ptr:
    description: Include PTR versions?
runs:
  using: composite
  steps:
    - name: Check for deprecated input
      if: ${{ inputs.flavor != '' }}
      run: |
        echo "Warning: The 'flavor' input is deprecated and will be removed in future versions. The addon flavor is now automatically determined from the TOC file(s)."
      shell: bash

    - name: Run TOC Updater
      uses: McTalian/wow-build-tools/toc/update@v1-beta
      with:
        args: -a ${{ inputs.addonDir }} ${{ inputs.beta != '' && '-b' || '' }} ${{ inputs.ptr != '' && '-p' || '' }}
